### ISSUE TITLE
Updating to v1.11 throws Fatal Error in ServerStreamingCallWrapper

### ISSUE THREAD

**Issue by taka-oyama** [googleapis/gax-php#361]
Seems like https://github.com/googleapis/gax-php/pull/347 broke the SpannerClient.

Upgrading to google/gax v1.11.0 produced the following error.

```
Fatal error: Uncaught TypeError: Argument 1 passed to Google\ApiCore\Transport\Grpc\ServerStreamingCallWrapper::__construct() must be an instance of Grpc\ServerStreamingCall, instance of Grpc\Gcp\GCPServerStreamCall given, called in /app/vendor/google/gax/src/Transport/GrpcTransport.php on line 208 and defined in /app/vendor/google/gax/src/Transport/Grpc/ServerStreamingCallWrapper.php:49
Stack trace:
#0 /app/vendor/google/gax/src/Transport/GrpcTransport.php(208): Google\ApiCore\Transport\Grpc\ServerStreamingCallWrapper->__construct(Object(Grpc\Gcp\GCPServerStreamCall))
#1 /app/vendor/google/gax/src/GapicClientTrait.php(608): Google\ApiCore\Transport\GrpcTransport->startServerStreamingCall(Object(Google\ApiCore\Call), Array)
#2 /app/vendor/google/gax/src/Middleware/CredentialsWrapperMiddleware.php(61): Google\Cloud\Spanner\V1\Gapic\SpannerGapicClient->Google\ApiCore\{closure}(Object(Google\ApiCore\Call), Array)
#3 /app/vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(66): Google\ApiCore\Middleware\CredentialsWrap in /app/vendor/google/gax/src/Transport/Grpc/ServerStreamingCallWrapper.php on line 49
```

It's only reproducible when I have `sysvshm` extensions enabled so I'm guessing it has something to do with https://github.com/googleapis/gax-php/blob/14e5bbd14b41c9602623a70d35e0d88fc8cddddf/src/GapicClientTrait.php#L211

#### Environment details

  - OS: Ubuntu
  - PHP version: 7.4
  - Package name and version: grpc v1.43

#### Steps to reproduce

  1. check out https://github.com/taka-oyama/grpc-bug-test.git
  2. switch branch to `gax-1.11-bug`
  3. run `docker-compose build && docker-compose run app`

#### Code example

Please see: https://github.com/taka-oyama/grpc-bug-test/blob/gax-1.11-bug/test.php

I sent the same issue to google-cloud-php since I didn't know which side to contact.
 https://github.com/googleapis/google-cloud-php/issues/5034

**Comment by taka-oyama** [comment]
fixed with  https://github.com/googleapis/gax-php/pull/362
